{% set name = "ics" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ics-py/ics.py/archive/v{{ version }}.tar.gz
  sha256: 4f24ca9843d8539565ca23600b7d17daa1a89fef3f5113ad2da01c7e1aebc6bd

build:
  noarch: python
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - tatsu >4.2
    - arrow <0.18,>=0.11
  run:
    - python >={{ python_min }}
    # upstream 0.7 requires arrow <0.15,>=0.11
    # but it cannot be satisfied with python 3.9 in conda (because arrow is not noarch)
    # I tested ics with arrow 0.15.8, 0.16.0, 0.17.0
    # and they all passes all tests
    - arrow <0.18,>=0.11
    - python-dateutil
    - six >1.5
    - tatsu >4.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - ics

about:
  home: https://github.com/ics-py/ics-py/
  license: Apache-2.0
  license_file: LICENSE.rst
  summary: "Pythonic iCalendar (RFC 5545) Parser"
  doc_url: https://icspy.readthedocs.io/en/stable/
  dev_url: https://github.com/C4ptainCrunch/ics.py/

extra:
  recipe-maintainers:
    - ickc
